README.md, cmd/manager/main.go, deploy/clusterrole.yaml, deploy/operator.yaml
A few updates to docs and permissions
=> Updates to permissions

deploy/olm-catalog/group-sync-operator/0.0.1/group-sync-operator.v0.0.1.clusterserviceversion.yaml, deploy/operator.yaml
Minor versioning enhancements with deployment and CSV
=> Minor versioning fixes

pkg/controller/constants/constants.go, pkg/controller/syncer/keycloak.go
added parent label
added children label
added support for generic labels
Signed-off-by: Raffaele Spazzoli <raffaele.spazzoli@gmail.com>
=> support for labels (limited to keycloak)

.github/workflows/group-sync-operator.yml
Tag management in GitHub action
=> Tag management in GitHub action

pkg/controller/constants/constants.go, pkg/controller/syncer/keycloak.go
Signed-off-by: Raffaele Spazzoli <raffaele.spazzoli@gmail.com>
=> fix parent label

deploy/olm-catalog/group-sync-operator/0.0.2/group-sync-operator.v0.0.2.clusterserviceversion.yaml, deploy/olm-catalog/group-sync-operator/0.0.2/redhatcop.redhat.io_groupsyncs_crd.yaml, deploy/olm-catalog/group-sync-operator/group-sync-operator.package.yaml, deploy/operator.yaml, version/version.go
Preparation for v0.0.2 release
=> Preparation for v0.0.2 release

README.md, deploy/clusterrole.yaml
Corrected issues with publishing events and updated documentation
=> Corrected issues with publishing events and updated documentation

deploy/olm-catalog/group-sync-operator/0.0.3/group-sync-operator.v0.0.3.clusterserviceversion.yaml, deploy/olm-catalog/group-sync-operator/0.0.3/redhatcop.redhat.io_groupsyncs_crd.yaml, deploy/olm-catalog/group-sync-operator/group-sync-operator.package.yaml, deploy/operator.yaml, version/version.go
=> Artifacts for 0.0.3 release

deploy/olm-catalog/group-sync-operator/0.0.4/group-sync-operator.v0.0.4.clusterserviceversion.yaml, deploy/olm-catalog/group-sync-operator/0.0.4/redhatcop.redhat.io_groupsyncs_crd.yaml, deploy/olm-catalog/group-sync-operator/group-sync-operator.package.yaml, deploy/operator.yaml, version/version.go
=> 0.0.4 release

pkg/controller/syncer/azure.go
Added support for limiting groups for Azure to resolve #32
=> Added support for limiting groups for Azure

deploy/olm-catalog/group-sync-operator/0.0.6/group-sync-operator.v0.0.6.clusterserviceversion.yaml, deploy/olm-catalog/group-sync-operator/0.0.6/redhatcop.redhat.io_groupsyncs_crd.yaml, deploy/olm-catalog/group-sync-operator/group-sync-operator.package.yaml, deploy/operator.yaml, version/version.go
Release of group-sync-operator 0.0.6
=> Release of group-sync-operator 0.0.6

Dockerfile, Makefile, README.md, config/crd/bases/redhatcop.redhat.io_groupsyncs.yaml, config/manager/kustomization.yaml, config/manifests/bases/group-sync-operator.clusterserviceversion.yaml
Doc updates and CSV/CRD changes
=> Doc updates and CSV/CRD changes

.github/workflows/pr.yml, .github/workflows/push.yml, config/manifests/bases/group-sync-operator.clusterserviceversion.yaml, go.mod, go.sum
Corrected several issues with pipeline and removed obsolete libraries
=> Fix libraries and pipeline

.github/workflows/push.yml
=> Push latest tag

README.md, config/manifests/bases/group-sync-operator.clusterserviceversion.yaml, config/rbac/kustomization.yaml, main.go
Resolves breaking issue with leader election
=> Resolves issue with leader election

Makefile
Template variables must have capital letter. after. each. point.
=> Template needs to use capital letters to work.

controllers/groupsync_controller.go, controllers/groupsync_controller_metrics.go, go.mod
Support for exposing operator metrics to resolve #73
=> Added metrics

.github/workflows/push.yml, config/default/manager_auth_proxy_patch.yaml, config/manifests/bases/group-sync-operator.clusterserviceversion.yaml, hack/attach_image_digests.sh
Support for disconnected environments
=> Support for relatedImages

Dockerfile
Configures image to run as nonroot
=> nonroot user account

api/v1alpha1/groupsync_types.go, config/manifests/bases/group-sync-operator.clusterserviceversion.yaml
=> CSV updates

.github/workflows/pr.yml, .github/workflows/push.yml, LICENSE, PROJECT, README.md, config/crd/bases/redhatcop.redhat.io_groupsyncs.yaml, config/helmchart/templates/_helpers.tpl, config/helmchart/templates/manager.yaml, config/helmchart/values.yaml.tpl, config/manager/manager.yaml, config/rbac/auth_proxy_role_binding.yaml, config/rbac/kustomization.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role_binding.yaml, config/rbac/service_account.yaml, config/scorecard/patches/basic.config.yaml, config/scorecard/patches/olm.config.yaml, go.mod, go.sum
=> Upgrade to OLM 1.5

config/manifests/bases/group-sync-operator.clusterserviceversion.yaml
=> Updated created date

.github/workflows/push.yml, hack/update_csv.sh
Automation to update `createdAt` and `containerImage` metadata
=> Updated CSV metadata

api/v1alpha1/groupsync_types.go, config/crd/bases/redhatcop.redhat.io_groupsyncs.yaml
Fixes #110 
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>
@sabre1041
=> make field required in order to avoid invalid labels

README.md, pkg/syncer/github.go, pkg/syncer/syncer.go
=> Drop username&password option

controllers/groupsync_controller.go, pkg/syncer/azure.go, pkg/syncer/github.go, pkg/syncer/gitlab.go, pkg/syncer/keycloak.go, pkg/syncer/okta.go
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>
=> avoid deprecated code

.github/workflows/push.yml
=> fix disconnected CSV support

.github/workflows/pr.yml, .github/workflows/push.yml, .gitignore, config/default/manager_auth_proxy_patch.yaml, config/helmchart/templates/service-account.yaml, config/helmchart/values.yaml.tpl, config/rbac/kustomization.yaml, config/rbac/service_account.yaml
Signed-off-by: raffaelespazzoli <raffaele.spazzoli@gmail.com>
=> fixed rbac

.github/dependabot.yaml
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>
=> add dependabot for gomodules

config/manifests/bases/group-sync-operator.clusterserviceversion.yaml
=> Updates to CSV

pkg/syncer/ldap.go
Added support for specifying CA using ConfigMap to LDAP to resolve #173
=> Added support for specifying CA using ConfigMap to LDAP

go.mod, go.sum
=> Updated protobuf dependency

.github/workflows/pr.yml, .github/workflows/push.yml
Pinned go workflow version and align with latest shared workflow
=> Pinned go workflow version

pkg/syncer/azure.go
Added paging support for Azure provider to resolve #184
=> Added paging support for Azure provider

.github/workflows/pr.yml, .github/workflows/push.yml
Revert workflow version to known working version
=> Revert workflow version

pkg/syncer/azure.go
Added checks to avoid NPE in azure provider
=> Added checks to avoid NPE in azure provider

pkg/syncer/azure.go
https://github.com/redhat-cop/group-sync-operator/issues/204
=> feat: get group members on $select

pkg/syncer/azure.go, pkg/syncer/github.go, pkg/syncer/gitlab.go, pkg/syncer/keycloak.go, pkg/syncer/ldap.go, pkg/syncer/okta.go
Some simple quotation marks were missing in logs.
=> Add missing single quote in logs

config/default/manager_auth_proxy_patch.yaml, config/helmchart/templates/manager.yaml
Removed kube auth proxy debug logging to resolve #216
=> Removed kube auth proxy debug logging

Dockerfile, config/default/manager_auth_proxy_patch.yaml, config/helmchart/templates/manager.yaml, config/manager/manager.yaml, main.go
Correct issue with lease migration + small code cleanup to remove unused `WATCH_NAMESPACE` environment variable
Resolved #234
=> Lease migration and cleanup

pkg/syncer/gitlab.go
Adding support for synchronizing GitLab Subgroup to resolve #219
=> Support for GitLab Subgroups

api/v1alpha1/groupsync_types.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/redhatcop.redhat.io_groupsyncs.yaml, config/manifests/bases/group-sync-operator.clusterserviceversion.yaml, pkg/syncer/azure.go
Added support for specifying certificate configurations for Azure
Resolves #232 #233
=> Added support for specifying certificate configurations for Azure

pkg/syncer/azure.go
Increased page size for group member query to resolve #246
=> Increased page size for group member query

README.md, api/v1alpha1/groupsync_types.go, config/crd/bases/redhatcop.redhat.io_groupsyncs.yaml, config/manifests/bases/group-sync-operator.clusterserviceversion.yaml, pkg/syncer/gitlab.go, pkg/syncer/syncer.go
Added support for specifying GitLab token types
Resolves #261
=> Gitlab token types

config/helmchart/templates/_helpers.tpl, config/helmchart/templates/manager.yaml, config/helmchart/values.yaml.tpl
Adding support for additional commonLabels as well as podLabels supplied in the values file.
=> helm-feat: Add support for commonLabels & podLabels

controllers/groupsync_controller.go
Refactored pruning and error handling logic
* No longer use annotation pruning method and instead pruning based on synchronized groups
* Improved error management to continue processing all providers regardless of error in other providers
=> Refactored pruning and error handling logic

main.go
Support for accessing resources explicitly in multiple namespaces to resolve #303
=> Support for accessing resources explicitly in multiple namespaces

pkg/syncer/azure.go
Added pagesize to all Azure invocations
Related to #246
=> Added pagesize to all Azure invocations

.github/workflows/pr.yml, .github/workflows/push.yml
Updated to latest reusable workflow
=> Updated to latest reusable workflow

Makefile, api/v1alpha1/groupsync_types.go, config/crd/bases/redhatcop.redhat.io_groupsyncs.yaml, config/manifests/bases/group-sync-operator.clusterserviceversion.yaml, controllers/groupsync_controller.go
Added support to ignore groups with invalid DNS 1035 names to resolve #270
=> Support for excluding invalid group names

config/manager/manager.yaml
Revert SA name change
related to #323
=> Revert SA name change

config/default/manager_auth_proxy_patch.yaml, config/helmchart/values.yaml.tpl
Update kube-rbac-proxy version
=> Update kube-rbac-proxy version

pkg/syncer/azure.go
Refactor transitive member management and improvements to group querying
Resolves #370
=> Refactor transitive member management and improvements to group querying
